### ISSUE TITLE
 org.apache.solr.common.SolrException: Too many values for UnInvertedField faceting on field text

### ISSUE THREAD

**Issue by conradjones** [jeroenvermeulen/magento-solarium#102]
Fails - Self Test

ERROR	Solr HTTP error: HTTP request failed, Operation timed out after 5001 milliseconds with 0 bytes received

Ubuntu 15.04
Tomcat 7 
1.6.9
-------------------------------------------------
INFO: [] webapp=/solr path=/select params={omitHeader=true&timeAllowed=5&spellcheck.alternativeTermCount=60&wt=json&json.nl=flat&q=SOLARIUMSELFTEST+143639877364481&start=0&rows=100&fl=product_id,score&df=text&sort=score+desc&fq=store_id:999999&group=true&group.field=product_id&group.limit=1&spellcheck=true&spellcheck.q=SOLARIUMSELFTEST+143639877364481&spellcheck.count=60&spellcheck.onlyMorePopular=true&spellcheck.extendedResults=true&spellcheck.accuracy=0.7} hits=1 status=0 QTime=47 
Jul 09, 2015 12:40:31 AM org.apache.solr.common.SolrException log
SEVERE: org.apache.solr.common.SolrException: Too many values for UnInvertedField faceting on field text
        at org.apache.solr.request.UnInvertedField.uninvert(UnInvertedField.java:390)
        at org.apache.solr.request.UnInvertedField.<init>(UnInvertedField.java:180)
        at org.apache.solr.request.UnInvertedField.getUnInvertedField(UnInvertedField.java:871)
        at org.apache.solr.request.SimpleFacets.getTermCounts(SimpleFacets.java:284)
        at org.apache.solr.request.SimpleFacets.getFacetFieldCounts(SimpleFacets.java:317)
        at org.apache.solr.request.SimpleFacets.getFacetCounts(SimpleFacets.java:195)
        at org.apache.solr.handler.component.FacetComponent.process(FacetComponent.java:72)
        at org.apache.solr.handler.component.SearchHandler.handleRequestBody(SearchHandler.java:186)
        at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:129)
        at org.apache.solr.core.SolrCore.execute(SolrCore.java:1376)
        at org.apache.solr.servlet.SolrDispatchFilter.execute(SolrDispatchFilter.java:365)
        at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:260)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:503)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:421)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1070)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611)
        at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:314)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:745)

**Comment by conradjones** [comment]
IT doesn't work with solr 3.x.
